name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        go-version: [ '1.17.x', '1.18.x', '1.19.x' ] # Use versions that support the required features

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: false
    - name: Print Go version
      run: go version
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
